"""sha-claim: Python SDK for Kenya SHA claims via the DHA AfyaConnect HIE eClaims API."""

from sha_claim.client import AsyncSHAClient
from sha_claim.domain.attachments import Attachment
from sha_claim.domain.benefits import (
    BedOccupancy,
    BenefitPackage,
    FundLimit,
    InterventionCoverage,
    SubBenefit,
    UtilizationBalance,
)
from sha_claim.domain.claim import (
    Blocker,
    ClaimAttachment,
    ClaimDiagnosis,
    ClaimIntervention,
    ClaimLine,
    CoverageSelection,
    Discharge,
    Invoice,
    LineAttachment,
    LineEdit,
    LineResubmission,
    NewClaimLine,
    NextOfKin,
    NextOfKinContact,
    PayerClaimRecord,
    Submission,
    VirtualClaim,
)
from sha_claim.domain.codes import (
    DocumentType,
    Icd11Code,
    InterventionCode,
    ProtocolCode,
    RegulationBody,
    SchemeCode,
)
from sha_claim.domain.consent import (
    Authorization,
    AuthorizedIntervention,
    BiometricContext,
    BiometricGuid,
    ElectivePreauth,
    MatchId,
    Otp,
    VerificationRequest,
)
from sha_claim.domain.eligibility import ConsentRoute, Coverage, Eligibility, Scheme
from sha_claim.domain.emergency import EmergencyCase, EmergencyProtocol, EmtClaim, ProtocolLine
from sha_claim.domain.enums import (
    AuthorizationStatus,
    BroughtBy,
    CancelReason,
    ClaimWorkflowState,
    CoverageStatus,
    DischargeReason,
    DoctorConsentRequestType,
    EligibilityStatus,
    IdentificationType,
    ModeOfArrival,
    NextOfKinIdType,
    PaymentMechanism,
    ServiceType,
)
from sha_claim.domain.files import DownloadLink, StoredFile
from sha_claim.domain.identifiers import (
    AttachmentId,
    ClaimGuid,
    ConsentToken,
    FacilityCode,
    InvoiceNumber,
    LineGuid,
    PatientId,
)
from sha_claim.domain.identity import BearerToken, Identity
from sha_claim.domain.money import Money
from sha_claim.domain.pomsf import (
    PomsfBalance,
    PomsfBenefit,
    PomsfFamilyMember,
    PomsfPolicy,
    policy_year_for,
)
from sha_claim.domain.practitioner import PractitionerRef
from sha_claim.domain.preauth import (
    DoctorConsentRequest,
    ImagingDetails,
    NoDetails,
    OncologyDetails,
    OpticalDetails,
    PreauthDetails,
    PreauthItem,
    Preauthorization,
    PreauthRequest,
    RenalDetails,
    SurgicalDetails,
)
from sha_claim.domain.preauth_vocabulary import (
    AnaesthesiaType,
    CarcinomaStaging,
    LensPrescription,
    MetastasisSite,
    NewOrReplacement,
    SessionFrequency,
    TreatmentSetting,
)
from sha_claim.domain.prescription import Dispense, DispensedProduct, Dosage, MedicationOrder, Prescription
from sha_claim.domain.registry import OtherIdentification, PatientContact, PatientRecord
from sha_claim.domain.schemes import belongs_to_scheme, canonical_scheme, scheme_family
from sha_claim.errors import (
    AuthenticationError,
    BadRequestError,
    ConfigurationError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitedError,
    RequestValidationError,
    ServerError,
    SHAClaimError,
    SubmissionOutcomeUnknownError,
    TransportError,
    UnexpectedResponseError,
)
from sha_claim.events import EventHook, SDKEvent
from sha_claim.facility import (
    FacilityScope,
    activate_facility,
    clear_facility,
    current_facility,
    facility_scope,
)
from sha_claim.session import ClaimSession
from sha_claim.settings import Environment, SHASettings, Timeouts

__version__ = "0.1.21"

__all__ = [
    "AnaesthesiaType",
    "AsyncSHAClient",
    "Attachment",
    "AttachmentId",
    "AuthenticationError",
    "Authorization",
    "AuthorizationStatus",
    "AuthorizedIntervention",
    "BadRequestError",
    "BearerToken",
    "BedOccupancy",
    "BenefitPackage",
    "BiometricContext",
    "BiometricGuid",
    "Blocker",
    "BroughtBy",
    "CancelReason",
    "CarcinomaStaging",
    "ClaimAttachment",
    "ClaimDiagnosis",
    "ClaimGuid",
    "ClaimIntervention",
    "ClaimLine",
    "ClaimSession",
    "ClaimWorkflowState",
    "ConfigurationError",
    "ConsentRoute",
    "ConsentToken",
    "Coverage",
    "CoverageSelection",
    "CoverageStatus",
    "Discharge",
    "DischargeReason",
    "Dispense",
    "DispensedProduct",
    "DoctorConsentRequest",
    "DoctorConsentRequestType",
    "DocumentType",
    "Dosage",
    "DownloadLink",
    "ElectivePreauth",
    "Eligibility",
    "EligibilityStatus",
    "EmergencyCase",
    "EmergencyProtocol",
    "EmtClaim",
    "Environment",
    "EventHook",
    "FacilityCode",
    "FacilityScope",
    "FileId",
    "FundLimit",
    "Icd11Code",
    "IdentificationType",
    "Identity",
    "ImagingDetails",
    "InterventionCode",
    "InterventionCoverage",
    "Invoice",
    "InvoiceNumber",
    "LensPrescription",
    "LineAttachment",
    "LineEdit",
    "LineGuid",
    "LineResubmission",
    "MatchId",
    "MedicationOrder",
    "MetastasisSite",
    "ModeOfArrival",
    "Money",
    "NewClaimLine",
    "NewOrReplacement",
    "NextOfKin",
    "NextOfKinContact",
    "NextOfKinIdType",
    "NoDetails",
    "NotFoundError",
    "OncologyDetails",
    "OpticalDetails",
    "OtherIdentification",
    "Otp",
    "PatientContact",
    "PatientId",
    "PatientRecord",
    "PayerClaimRecord",
    "PaymentMechanism",
    "PermissionDeniedError",
    "PomsfBalance",
    "PomsfBenefit",
    "PomsfFamilyMember",
    "PomsfPolicy",
    "PractitionerRef",
    "PreauthDetails",
    "PreauthItem",
    "PreauthRequest",
    "Preauthorization",
    "Prescription",
    "ProtocolCode",
    "ProtocolLine",
    "RateLimitedError",
    "RegulationBody",
    "RenalDetails",
    "RequestValidationError",
    "SDKEvent",
    "SHAClaimError",
    "SHASettings",
    "Scheme",
    "SchemeCode",
    "ServerError",
    "ServiceType",
    "SessionFrequency",
    "StoredFile",
    "SubBenefit",
    "Submission",
    "SubmissionOutcomeUnknownError",
    "SurgicalDetails",
    "Timeouts",
    "TransportError",
    "TreatmentSetting",
    "UnexpectedResponseError",
    "UtilizationBalance",
    "VerificationRequest",
    "VirtualClaim",
    "__version__",
    "activate_facility",
    "belongs_to_scheme",
    "canonical_scheme",
    "clear_facility",
    "current_facility",
    "facility_scope",
    "policy_year_for",
    "scheme_family",
]
