"""sha-claim: Python SDK for Kenya SHA claims via the DHA AfyaConnect HIE eClaims API."""

from sha_claim.client import AsyncSHAClient
from sha_claim.domain.attachments import Attachment
from sha_claim.domain.benefits import BenefitPackage, InterventionCoverage, SubBenefit
from sha_claim.domain.claim import (
    ClaimAttachment,
    ClaimDiagnosis,
    ClaimIntervention,
    ClaimLine,
    Discharge,
    Invoice,
    LineEdit,
    LineResubmission,
    NewClaimLine,
    NextOfKin,
    NextOfKinContact,
    PayerClaimRecord,
    VirtualClaim,
)
from sha_claim.domain.codes import DocumentType, Icd11Code, InterventionCode, RegulationBody, SchemeCode
from sha_claim.domain.consent import Authorization, AuthorizedIntervention, BiometricGuid, MatchId, Otp
from sha_claim.domain.eligibility import Coverage, Eligibility, Scheme
from sha_claim.domain.enums import (
    AuthorizationStatus,
    CancelReason,
    CoverageStatus,
    DischargeReason,
    DoctorConsentRequestType,
    EligibilityStatus,
    IdentificationType,
    NextOfKinIdType,
    PaymentMechanism,
    ServiceType,
)
from sha_claim.domain.identifiers import (
    AttachmentId,
    ClaimGuid,
    ConsentToken,
    FacilityCode,
    InvoiceNumber,
    LineGuid,
    PatientId,
)
from sha_claim.domain.money import Money
from sha_claim.domain.practitioner import PractitionerRef
from sha_claim.domain.preauth import DoctorConsentRequest, PreauthItem, Preauthorization, PreauthRequest
from sha_claim.errors import (
    AuthenticationError,
    BadRequestError,
    ConfigurationError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitedError,
    RequestValidationError,
    ServerError,
    SHAClaimError,
    SubmissionOutcomeUnknownError,
    TransportError,
    UnexpectedResponseError,
)
from sha_claim.session import ClaimSession
from sha_claim.settings import Environment, SHASettings, Timeouts

__version__ = "0.1.0.dev0"

__all__ = [
    "AsyncSHAClient",
    "Attachment",
    "AttachmentId",
    "AuthenticationError",
    "Authorization",
    "AuthorizationStatus",
    "AuthorizedIntervention",
    "BadRequestError",
    "BenefitPackage",
    "BiometricGuid",
    "CancelReason",
    "ClaimAttachment",
    "ClaimDiagnosis",
    "ClaimGuid",
    "ClaimIntervention",
    "ClaimLine",
    "ClaimSession",
    "ConfigurationError",
    "ConsentToken",
    "Coverage",
    "CoverageStatus",
    "Discharge",
    "DischargeReason",
    "DoctorConsentRequest",
    "DoctorConsentRequestType",
    "DocumentType",
    "Eligibility",
    "EligibilityStatus",
    "Environment",
    "FacilityCode",
    "Icd11Code",
    "IdentificationType",
    "InterventionCode",
    "InterventionCoverage",
    "Invoice",
    "InvoiceNumber",
    "LineEdit",
    "LineGuid",
    "LineResubmission",
    "MatchId",
    "Money",
    "NewClaimLine",
    "NextOfKin",
    "NextOfKinContact",
    "NextOfKinIdType",
    "NotFoundError",
    "Otp",
    "PatientId",
    "PayerClaimRecord",
    "PaymentMechanism",
    "PermissionDeniedError",
    "PractitionerRef",
    "PreauthItem",
    "PreauthRequest",
    "Preauthorization",
    "RateLimitedError",
    "RegulationBody",
    "RequestValidationError",
    "SHAClaimError",
    "SHASettings",
    "Scheme",
    "SchemeCode",
    "ServerError",
    "ServiceType",
    "SubBenefit",
    "SubmissionOutcomeUnknownError",
    "Timeouts",
    "TransportError",
    "UnexpectedResponseError",
    "VirtualClaim",
    "__version__",
]
